version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: "chore(deps):"
    labels:
      - dependencies
    open-pull-requests-limit: 10
    groups:
      typescript-eslint:
        patterns:
          - "@typescript-eslint/*"
      vitest:
        patterns:
          - "vitest"
          - "@vitest/*"
      minor-and-patch:
        update-types:
          - "minor"
          - "patch"
        exclude-patterns:
          - "@typescript-eslint/*"
          - "vitest"
          - "@vitest/*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: "chore(ci):"
    labels:
      - ci
    groups:
      actions:
        patterns:
          - "*"
